security:
    role_hierarchy:
        ROLE_COMPANY:     ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_COMPANY]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                success_handler: login_success_handler

            logout:
                path:   /logout
                target: homepage

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/company, roles: ROLE_COMPANY }

    providers:
        main:
            entity: { class: Eti\JobeetBundle\Entity\User, property: username }

    encoders:
        Eti\JobeetBundle\Entity\User: sha512
