eti_affiliate_new:
    path:  /new
    defaults: { _controller: "EtiJobeetBundle:Affiliate:new" }
eti_affiliate_create:
    path: /create
    defaults: { _controller: "EtiJobeetBundle:Affiliate:create" }
    methods: POST
eti_affiliate_wait:
    path: /wait
    defaults: { _controller: "EtiJobeetBundle:Affiliate:wait" }