eti_job:
    path:     /
    defaults: { _controller: "EtiJobeetBundle:Job:index" }

eti_job_show:
    path:     /job/{company}/{location}/{id}/{position}
    defaults: { _controller: "EtiJobeetBundle:Job:show" }
    requirements:
        id: '\d+'

eti_job_preview:
    path:  job/{company}/{location}/{token}/{position}
    defaults: { _controller: "EtiJobeetBundle:Job:preview" }
    requirements:
        token:  '\w+'

eti_job_publish:
    path:  job/{token}/publish
    defaults: { _controller: "EtiJobeetBundle:Job:publish" }
    methods:  POST

eti_job_create:
    path:     /company/job/create
    defaults: { _controller: "EtiJobeetBundle:Company:createJob" }
    methods:  POST

eti_job_edit:
    path:     /job/{token}/edit
    defaults: { _controller: "EtiJobeetBundle:Job:edit" }
    requirements:
        token:  '\w+'

eti_job_update:
    path:     /job/{token}/update
    defaults: { _controller: "EtiJobeetBundle:Job:update" }
    methods:  [POST]
    requirements:
        token:  '\w+'

eti_job_delete:
    path:     /job/{token}/delete
    defaults: { _controller: "EtiJobeetBundle:Job:delete" }
    methods:  [POST]
    requirements:
        token: '\w+'

eti_job_extend:
    path:  /{token}/extend
    defaults: { _controller: "EtiJobeetBundle:Job:extend" }
    methods: POST

eti_job_delete_job_ajax:
    path: /delete/job/{id}
    defaults: { _controller: "EtiJobeetBundle:Job:deleteAjax" }

eti_job_search:
    path: /job/search
    defaults: { _controller: "EtiJobeetBundle:Job:search" }