login:
    path:   /login
    defaults:  { _controller: IRecruitBundle:Default:login }
login_check:
    path:   /login_check
logout:
    path:   /logout

user_register:
    path:   /register
    defaults:  { _controller: IRecruitBundle:Default:register }

homepage:
    path:   /home
    defaults:  { _controller: IRecruitBundle:Default:homepage }

joblists:
    path:   /joblists
    defaults:  { _controller: IRecruitBundle:Default:jobList }

user_dashboard:
    path:   /user/dashboard
    defaults:  { _controller: IRecruitBundle:User:dashboard}


profile:
    path:   /user/profile
    defaults:  { _controller: IRecruitBundle:User:profile}

cv_upload:
    path:   /user/uploadcv
    defaults:  { _controller: IRecruitBundle:User:uploadCv}

user_cv:
    path:   /user/cv
    defaults:  { _controller: IRecruitBundle:User:viewPDF}

viewUser:
    path:   /view/user/{id}
    defaults:  { _controller: IRecruitBundle:User:viewProfile}
    requirements: {id: "\d+"}

company_dashboard:
    path:   /company/dashboard
    defaults:  { _controller: IRecruitBundle:Company:dashboard}

cprofile:
    path:   /company/profile
    defaults:  { _controller: IRecruitBundle:Company:profile}

viewCompany:
    path:   /view/company/{id}
    defaults:  { _controller: IRecruitBundle:Company:viewProfile}
    requirements: {id: "\d+"}

newJob:
    path:   /company/job/new
    defaults:  { _controller: IRecruitBundle:Job:newJob}

newJobModalDisplay:
    path:   /job/modaldisplay/{id}
    defaults:  { _controller: IRecruitBundle:Company:newJobModalDisplay}
    requirements: {id: "-?\d+"}

viewPDF:
    path:   /cv/{id}
    defaults:  { _controller: IRecruitBundle:Company:viewPDF}
    requirements: {id: "\d+"}

company_jobs:
    path:   /company/myjobs
    defaults:  { _controller: IRecruitBundle:Company:list}

applicants:
    path:   /company/{id}/applicants
    defaults:  { _controller: IRecruitBundle:Company:viewApplicants}
    requirements: {id: "\d+"}

applyJob:
    path:   /apply/job/{id}
    defaults:  { _controller: IRecruitBundle:Job:applyJob}
    requirements: {id: "\d+"}

jobCreate:
    path:     /company/job/create
    defaults: { _controller: IRecruitBundle:Job:createJob }
    methods:  POST|GET

jobExtend:
    path:     /company/job/extend
    defaults: { _controller: IRecruitBundle:Job:jobExtend }

editJob:
    path:   /company/editjob/{id}
    defaults:  { _controller: IRecruitBundle:Job:editJob}
    requirements: {id: "\d+"}
