IRecruitBundle\Entity\UProfile:
    type: entity
    table: u_profile
    repositoryClass: IRecruitBundle\Repository\UProfileRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firstName:
            type: string
            nullable: false
        lastName:
            type: string
            length: 255
            nullable: false
        birthDate:
            type: date
            nullable: false
        image:
            type: string
            nullable: true
        curriculumVitae:
            type: string
            nullable: true
        phone:
            type: string
            nullable: false
        gender:
            type: boolean
            nullable: false
        address:
            type: string
            nullable: true
        city:
            type: string
            nullable: false
        birthPlace:
            type: string
            nullable: true
        skills:
            type: string
            nullable: true
        objectives:
            type: string
            nullable: true
        description:
            type: text
            nullable: true
        country:
            type: string
            nullable: false
        facebook:
            type: string
            nullable: true
        linkedin:
            type: string
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    oneToOne:
        user:
            targetEntity: User
            inversedBy:   profile
            cascade: ["persist"]
            joinColumn:
                name: id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, setTokenValue ]
        preUpdate: [ setUpdatedAtAtValue ]