eti_jobeet_eti_job:
    resource: "@EtiJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /
eti_jobeet_eti_affiliate:
    resource: "@EtiJobeetBundle/Resources/config/routing/affiliate.yml"
    prefix:   /affiliate

eti_jobeet_homepage:
    path:     /
    defaults: { _controller: EtiJobeetBundle:Job:index }
eti_jobeet_category:
    path:  /category/{slug}/{page}
    defaults: { _controller: EtiJobeetBundle:Category:show, page: 1 }
eti_jobeet_api:
    pattern: /api/{token}/jobs.{_format}
    defaults: {_controller: "EtiJobeetBundle:Api:list"}
    requirements:
        _format: xml|json|yaml
login:
    path:   /login
    defaults:  { _controller: EtiJobeetBundle:Default:login }
login_check:
    path:   /login_check
logout:
    path:   /logout

test:
    path:   /test
    defaults:  { _controller: EtiJobeetBundle:Default:test }

homepage:
    path:   /home
    defaults:  { _controller: EtiJobeetBundle:Default:homepage }


company_dashboard:
    path:   /company/dashboard
    defaults:  { _controller: EtiJobeetBundle:Company:dashboard}

user_dashboard:
    path:   /user/dashboard
    defaults:  { _controller: EtiJobeetBundle:User:dashboard}

joblists:
    path:   /joblists
    defaults:  { _controller: EtiJobeetBundle:Company:jobList }

profile:
    path:   /user/profile
    defaults:  { _controller: EtiJobeetBundle:User:profile}

profile:
    path:   /company/profile
    defaults:  { _controller: EtiJobeetBundle:Company:profile}

