services:
    sonata.admin.category:
        class: Eti\JobeetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        arguments:
            - ~
            - Eti\JobeetBundle\Entity\Category
            - 'EtiJobeetBundle:Admin\CategoryAdmin'
        calls:
            - [ setTranslationDomain, [backend]]
    sonata.admin.job:
        class: Eti\JobeetBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Job" }
        arguments:
            - ~
            - Eti\JobeetBundle\Entity\Job
            - 'EtiJobeetBundle:Admin\JobAdmin'
        calls:
            - [ setTranslationDomain, [backend]]
    sonata.admin.affiliate:
        class: Eti\JobeetBundle\Admin\AffiliateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Affiliate" }
        arguments:
            - ~
            - Eti\JobeetBundle\Entity\Affiliate
            - 'EtiJobeetBundle:Admin\AffiliateAdmin'