Eti\JobeetBundle\Entity\Category:
    type: entity
    repositoryClass: Eti\JobeetBundle\Repository\CategoryRepository
    table: category
    id:
        id:
            type: integer
            id: true
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: category
    manyToMany:
        affiliates:
            targetEntity: Affiliate
            mappedBy: categories
    lifecycleCallbacks:
        prePersist: [ setSlugValue ]
        preUpdate: [ setSlugValue ]