Eti\JobeetBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToOne:
        company:
            targetEntity: Company
            mappedBy:     user
        profile:
            targetEntity: Profile
            mappedBy:     user
