Eti\JobeetBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToOne:
        company:
            targetEntity: Eti\JobeetBundle\Entity\CProfile
            mappedBy:     user
        profile:
            targetEntity: UProfile
            mappedBy:     user

    manyToMany:
        jobs:
          targetEntity: Job
          mappedBy: users
