<?php

namespace IRecruitBundle\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
