<?php

namespace IRecruitBundle\Repository;

use IRecruitBundle\Entity\Job;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActiveJobs($categoryId = null, $max = null, $offset = null, $affiliateId = null)
    {
        $qb = $this->createQueryBuilder('j')
            ->where('j.expiresAt > :date')
            ->setParameter('date', date('Y-m-d H:i:s', time()))
            ->andWhere('j.isActivated = :activated')
            ->setParameter('activated', 1)
            ->orderBy('j.expiresAt', 'DESC');

        if ($max) {
            $qb->setMaxResults($max);
        }

        if ($offset) {
            $qb->setFirstResult($offset);
        }

        if ($categoryId) {
            $qb->andWhere('j.categoryId = :categoryId')
                ->setParameter('categoryId', $categoryId);
        }

        if ($affiliateId) {
            $qb->leftJoin('j.category', 'c')
                ->leftJoin('c.affiliates', 'a')
                ->andWhere('a.id = :affiliateId')
                ->setParameter('affiliateId', $affiliateId)
            ;
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }

    public function countActiveJobs($categoryId = null)
    {
        $qb = $this->createQueryBuilder('j')
            ->select('count(j.id)')
            ->where('j.expiresAt > :date')
            ->setParameter('date', date('Y-m-d H:i:s', time()))
            ->andWhere('j.isActivated = :activated')
            ->setParameter('activated', 1);
            ;
     
        if ($categoryId) {
            $qb->andWhere('j.category = :categoryId')
            ->setParameter('categoryId', $categoryId);
        }
     
        $query = $qb->getQuery();
     
        return $query->getSingleScalarResult();
    }

    public function getActiveJob($id)
    {
        $query = $this->createQueryBuilder('j')
            ->where('j.id = :id')
            ->setParameter('id', $id)
            ->andWhere('j.expiresAt > :date')
            ->setParameter('date', date('Y-m-d H:i:s', time()))
            ->andWhere('j.isActivated = :activated')
            ->setParameter('activated', 1)
            ->setMaxResults(1)
            ->getQuery();
 
        $job = $query->getOneOrNullResult();
 
        return $job;
    }

    public function cleanup($days)
    {
        $query = $this->createQueryBuilder('j')
            ->delete()
            ->where('j.isActivated IS NULL')
            ->andWhere('j.createdAt < :createdAt')    
            ->setParameter('createdAt',  date('Y-m-d', time() - 86400 * $days))
            ->getQuery();
     
        return $query->execute();
    }

    public function getLatestPost($categoryId = null)
    {
        $query = $this->createQueryBuilder('j')
            ->where('j.expiresAt > :date')
            ->setParameter('date', date('Y-m-d H:i:s', time()))
            ->andWhere('j.isActivated = :activated')
            ->setParameter('activated', 1)
            ->orderBy('j.expiresAt', 'DESC')
            ->setMaxResults(1);
 
        if($categoryId) {
            $query->andWhere('j.category = :categoryId')
                ->setParameter('categoryId', $categoryId);
        }
 
        try{
            $job = $query->getQuery()->getSingleResult();
        } catch(\Doctrine\Orm\NoResultException $e){
            $job = null;
        }
 
        return $job;    
    }

    public function findByCriteria($searchTerm, $company, $category, $position, $location)
    {
        $q = $this->createQueryBuilder('j')
            ->where('j.expiresAt> :now')
            ->setParameter('now', new \DateTime())
        ;
        if($searchTerm){
            $q
                ->join('j.company', 'co')
                ->join('j.category', 'cat')
                ->andWhere('(j.position LIKE :searchTerm OR co.name LIKE :searchTerm OR j.location LIKE :searchTerm OR cat.name LIKE :searchTerm)')
                ->setParameter('searchTerm', "%$searchTerm%")
            ;
        }
        if($company){
            $q
                ->andWhere('j.company =:company')
                ->setParameter('company', $company)
            ;
        }
        if($location){
            $q
                ->andWhere('j.location LIKE :location')
                ->setParameter('location', "%$location%")
            ;
        }
        if($position){
            $q
                ->andWhere('j.position LIKE :position')
                ->setParameter('position', "%$position%")
            ;
        }
        if($category){
            $q
                ->andWhere('j.category =:category')
                ->setParameter('category', $category)
            ;
        }


        return $q
            ->getQuery()
            ->getResult();
    }

    public function findByCompanyId($companyid){
        return $this->createQueryBuilder('job')
            ->join('job.users','users')
            -> andWhere('job.company =:companyid')
            ->setParameter('companyid',$companyid)
            ->getQuery()->getResult()
        ;
    }
}
