<?php

namespace IRecruitBundle\Repository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
